### Linear Regression Multiple Variables

We are going to predict houseprice from multiple variables in the given data sets. We use Machine learning algorithm Linear Regression Multiple Variables

Linear Equation we use is, y = m1x1 + m2x2 + m3x3 + b

Where,

m1,m2,m3 = coefficients, reg.coef_
 
b = intercept, reg.intercept_

x1,x2,x3 = the predicting values

First let us import required libraries

In [49]:
import pandas as pd
import numpy as np
import math
from sklearn import linear_model
print("Imported")

Imported


Let us load the data set into data frame using pandas

In [50]:
df = pd.read_csv("homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

As we can see there is null value in the data set first we need to clean the data. Let us fill the data with mean value. I believe that it is a bit accurate like an average accurate value.

In [51]:
df.bedrooms.mean()

4.2

In [52]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.mean())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.2   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

Well we have filled the value with mean value in the bedroom column. Now let us fit this data into the regression model and predict the homeprice of home that has,

3000 sqr ft area, 3 bedrooms, 40 year old

2500 sqr ft area, 4 bedrooms, 5 year old


In [53]:
reg = linear_model.LinearRegression()
reg.fit(df[["area", "bedrooms", "age"]],df.price)

LinearRegression()

Now we have created the linear regression model let us predict the prices

In [55]:
reg.predict([[3000, 3, 40]])

/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([490833.34243748])

In [56]:
reg.coef_

array([  116.66950551, 18756.28806982, -3675.75111708])

In [57]:
reg.intercept_

231586.0063940916

In [58]:
y = 116.66950551 * 3000 + 3 * 18756.28806982 + 40 * -3675.75111708 + 231586.0063940916
y

490833.34245035157

In [59]:
reg.predict([[2500,4,5]])

/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([579906.16685223])

Let us work on other file

In [60]:
df1 = pd.read_csv("hiring.csv")
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [61]:
df1.experience = df1.experience.fillna("zero")
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [71]:
from text2digits import text2digits

t2d = text2digits.Text2Digits()

# Convert all values in the 'experience' column to strings
df1['experience'] = df1['experience'].astype(str)

# Apply the text2digits conversion
df1['experience'] = df1['experience'].apply(t2d.convert)

# If needed, convert back to integers
df1['experience'] = df1['experience'].astype(int)

# df1.experience = df1.experience.apply(w2n.word_to_num)
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [28]:
df1["test_score(out of 10)"].mean()

7.857142857142857

In [74]:
df1["test_score(out of 10)"] = df1["test_score(out of 10)"].fillna(df1["test_score(out of 10)"].mean())
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0               8.000000                           9      50000
1           0               8.000000                           6      45000
2           5               6.000000                           7      60000
3           2              10.000000                          10      65000
4           7               9.000000                           6      70000
5           3               7.000000                          10      62000
6          10               7.857143                           7      72000
7          11               7.000000                           8      80000

In [79]:
df1['experience'] = pd.to_numeric(df1['experience'], errors='coerce')
df1['test_score(out of 10)'] = pd.to_numeric(df1['test_score(out of 10)'], errors='coerce')
df1['interview_score(out of 10)'] = pd.to_numeric(df1['interview_score(out of 10)'], errors='coerce')
X = df1[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']]
Y = df1['salary($)']
reg1 = linear_model.LinearRegression()
reg1.fit(X,Y)

LinearRegression()

In [81]:
reg1.predict([[2,9,6]])

/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53290.89255945])

In [82]:
reg1.predict([[12,10,10]])

/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92268.07227784])